# Pandas module
- 一個資料處理和分析工具，Python版的Excel
- 需先安裝pandas模組
- 提供兩種資料結構 Series, DataFrame 及其運算操作

![pandas dataframe and series](https://www.altexsoft.com/static/blog-post/2024/2/a2b6d6bd-898e-424f-98a8-50b3bdf775eb.webp)

# Operate Series
- Series 是一維陣列，類似Excel中的一欄
- Series 可以內定索引(0, 1, 2, ...)或自訂索引，用來標示資料的位置，類似於Excel中的列號
- Series 可以進行各種資料操作和分析，例如篩選、排序、統計等
- Series 的建立語法: `pd.Series(data, index=index)`

In [3]:
# Create Series
import pandas as pd
name_list = ['王小明','李小美','陳大同','林小玉']
score_list = [65, 90, 81, 79]
# scores = pd.Series(score_list)
scores = pd.Series(score_list, index=name_list)

scores

王小明    65
李小美    90
陳大同    81
林小玉    79
dtype: int64

In [4]:
# Understand Series statistics
scores.describe() # summary statistics

count     4.000000
mean     78.750000
std      10.340052
min      65.000000
25%      75.500000
50%      80.000000
75%      83.250000
max      90.000000
dtype: float64

In [8]:
# Indexing Series
print(scores['王小明']) # access by index label
print(scores.iloc[0]) # access by index position
print(scores.loc['王小明']) # access by index label
# print(scores[1])     # access by index position (not recommended)
# print(scores.ENG)    # access by attribute (not recommended)

65
65
65

In [9]:
# Modify Series
scores['王小明'] = 100 # modify by index label
scores.iloc[2] = 50     # modify by index position
scores.loc['林小玉'] = 95    # modify by index label
scores

王小明    100
李小美     90
陳大同     50
林小玉     95
dtype: int64

In [13]:
# Slicing Series
scores['王小明':'陳大同'] # 連續 slicing by index label
scores[1:3] # 連續 slicing by index position (not include the end position)
scores[['陳大同','王小明', '林小玉']] # 不連續 slicing

陳大同     50
王小明    100
林小玉     95
dtype: int64

## Lab of Series
根據下列表格資料，創建一個 Series (city_revenues), 回答下列問題
city | revenues
-----|---------
Amsterdam|4200
Toronto|8000
Tokyo|6500

- Toronto 的 revenues 是多少
- 第零筆資料的 revenues 是多少
- 最後一筆資料的 revenues 是多少
- 求 revenues 的 sum

# Operate DataFrame
- DataFrame 是一個二維的資料結構，類似於Excel中的試算表
- DataFrame 由多個 Series 組成，每個 Series 是 DataFrame 的一欄
- DataFrame 可以有列號和欄號的內定索引(0, 1, 2, ...)或自訂列號和欄號索引，用來標示資料的位置
- DataFrame 可以進行各種資料操作和分析，例如篩選、排序、分組、合併等
- DataFrame 的建立語法: `pd.DataFrame(data, index=index, columns=columns)`

In [153]:
# Create DataFrame
import pandas as pd
# 設定row index 跟column label
name_list = ['王小明','李小美','陳大同','林小玉']
subject_list = ['國文','英文','數學','自然','社會']
credit_list=  [[65,92,78,83,70],
       [90,72,76,93,56],
       [81,85,91,89,77],
       [79,53,47,94,80],
       ]
df = pd.DataFrame(credit_list,
                  index=name_list,
                  columns=subject_list)
df

     國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  77
林小玉  79  53  47  94  80

In [87]:
# Understand DataFrame
df.shape
# df.dtypes
# df.describe()
# df.head(3)
# df.tail(2)

(4, 5)

In [ ]:
# Read single row and column from DataFrame
# df['英文'] # access by column label, return a Series
# df.loc['王小明'] # access by row index label, return a Series
# df.iloc[0]      # access by row index position, return a Series
print(df.loc['王小明','英文']) # access by row index label and column label
print(df.iloc[0,1])       # access by row index position and column position
df

92
92

     國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  77
林小玉  79  53  47  94  80

In [124]:
# Read multiple rows and columns from DataFrame
df[['英文','自然']]
df.loc[['王小明','林小玉']]
df.iloc[[1,2]]
df.loc[['王小明','林小玉'],['英文','自然']]
df.loc[:,'英文':'自然']
df.iloc[0:2,1:4]
df.iloc[[0,3],[1,3]]

     英文  自然
王小明  92  83
林小玉  53  94

# Use Case of DataFrame
[A. 大學學測成績計算](https://github.com/mingfujacky/Lecture-Python/blob/main/pandas/pandas_basic.ipynb)<br>

[B. DataFrame 資料運算](https://github.com/mingfujacky/Lecture-Python/blob/main/pandas/pandas_middle.ipynb)<br>

# 學習地圖 - Pandas 功能整理
### 超圖解資料科學 ✕ 機器學習 實戰探索：使用 Python

![](file/image/pandas_recap_1.jpg)