# Class Lab: Discover Association Rules by Apriori Algorithm

## Step 1: setup goal
- use Apriori algorithm to discover association riles

## Step 2: retrieve data
use dummy data for demonstration

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# prepare transaction
transactions = [
    ['Milk', 'Bread', 'Butter'],   # T1
    ['Beer', 'Bread'],             # T2
    ['Milk', 'Beer', 'Butter'],    # T3
    ['Milk', 'Bread', 'Beer'],     # T4
    ['Milk', 'Bread', 'Butter'],   # T5
]
transactions

[['Milk', 'Bread', 'Butter'],
 ['Beer', 'Bread'],
 ['Milk', 'Beer', 'Butter'],
 ['Milk', 'Bread', 'Beer'],
 ['Milk', 'Bread', 'Butter']]

## Step 3: prepare data

In [2]:
# convert to one-hot encoding (boolean dataframe)
# fit() ensures we know the set of items (columns).
# transform() uses that set to consistently encode the transactions.
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

    Beer  Bread  Butter   Milk
0  False   True    True   True
1   True   True   False  False
2   True  False    True   True
3   True   True   False   True
4  False   True    True   True

## Step 4: explore data

In [3]:
# Find frequent itemsets
min_support = 0.4
freq_itemsets = apriori(df, min_support=min_support, use_colnames=True)
freq_itemsets = freq_itemsets.sort_values(['support', 'itemsets'], ascending=[False, True])
freq_itemsets

   support               itemsets
1      0.8                (Bread)
3      0.8                 (Milk)
0      0.6                 (Beer)
2      0.6               (Butter)
7      0.6          (Milk, Bread)
8      0.6         (Milk, Butter)
4      0.4          (Beer, Bread)
5      0.4           (Beer, Milk)
6      0.4        (Bread, Butter)
9      0.4  (Milk, Bread, Butter)

## Step 5: build model
Comparing the accuracy of the original data set with latent variables

In [11]:
# Generate association rules
min_conf = 0.60
rules = association_rules(freq_itemsets, metric="confidence", min_threshold=min_conf)
rules[["antecedents", "consequents", "support", "confidence"]]

        antecedents    consequents  support  confidence
0            (Milk)        (Bread)      0.6    0.750000
1           (Bread)         (Milk)      0.6    0.750000
2            (Milk)       (Butter)      0.6    0.750000
3          (Butter)         (Milk)      0.6    1.000000
4            (Beer)        (Bread)      0.4    0.666667
5            (Beer)         (Milk)      0.4    0.666667
6          (Butter)        (Bread)      0.4    0.666667
7     (Milk, Bread)       (Butter)      0.4    0.666667
8    (Milk, Butter)        (Bread)      0.4    0.666667
9   (Bread, Butter)         (Milk)      0.4    1.000000
10         (Butter)  (Milk, Bread)      0.4    0.666667

## Step 6: presentation

In [10]:
def fs_to_str(fs): 
    return "{" + ", ".join(sorted(fs)) + "}"

if len(rules) == 0:
    print("（沒有符合條件的規則）")
else:
    display_cols = ['antecedents', 'consequents', 'support', 'confidence', 'lift', 'leverage', 'conviction']
    pretty = rules.copy()
    pretty['antecedents'] = pretty['antecedents'].apply(fs_to_str)
    pretty['consequents'] = pretty['consequents'].apply(fs_to_str)
pretty[["antecedents", "consequents", "support", "confidence"]].round(2)

        antecedents    consequents  support  confidence
0            {Milk}        {Bread}      0.6        0.75
1           {Bread}         {Milk}      0.6        0.75
2            {Milk}       {Butter}      0.6        0.75
3          {Butter}         {Milk}      0.6        1.00
4            {Beer}        {Bread}      0.4        0.67
5            {Beer}         {Milk}      0.4        0.67
6          {Butter}        {Bread}      0.4        0.67
7     {Bread, Milk}       {Butter}      0.4        0.67
8    {Butter, Milk}        {Bread}      0.4        0.67
9   {Bread, Butter}         {Milk}      0.4        1.00
10         {Butter}  {Bread, Milk}      0.4        0.67