# Lab: Preprocess students scores
This lab demonstrates how to preprocess students scores data using Python and Pandas.<br>
The dataset contains 40 students' scores in 5 exams <br>
We will perform data cleaning and transformation to prepare it for analysis.

In [1]:
from pathlib import Path
import pandas as pd

### Load file

In [2]:
source_file = Path.cwd() / '../csv/student_scores.csv'
df = pd.read_csv(source_file)
df.head()

,ID,name,sex,email,第1次平時考,第2次平時考,第3次平時考,第4次平時考,第5次平時考
0,1080001,丁軒軒,男,1080001@sun.tc.edu.tw,86,88.0,82.0,87,92.0
1,1080002,王倫樺,女,1080002@sun.tc.edu.tw,92,100.0,95.0,99,96.0
2,1080003,何宜敏,女,1080003@sun.tc.edu.tw,82,87.0,86.0,82,82.0
3,1080004,何志陞,男,1080004@sun.tc.edu.tw,91,92.0,99.0,91,92.0
4,1080005,吳ㄧ歌,女,1080005@sun.tc.edu.tw,93,NaN,92.0,97,98.0

### Understand data

In [3]:
df.shape
df.dtypes
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      41 non-null     int64
 1   name    41 non-null     object
 2   sex     41 non-null     object
 3   email   41 non-null     object
 4   第1次平時考  41 non-null     int64
 5   第2次平時考  39 non-null     float64
 6   第3次平時考  40 non-null     float64
 7   第4次平時考  41 non-null     int64
 8   第5次平時考  40 non-null     float64
dtypes: float64(3), int64(3), object(3)
memory usage: 3.0+ KB

In [4]:
# change column names to english use replace method
df = df.rename(columns={
    'ID': 'id',
    '第1次平時考': 'exam1',
    '第2次平時考': 'exam2',
    '第3次平時考': 'exam3',
    '第4次平時考': 'exam4',
    '第5次平時考': 'exam5'
})
df.head()

        id name sex                  email  exam1  exam2  exam3  exam4  exam5
0  1080001  丁軒軒   男  1080001@sun.tc.edu.tw     86   88.0   82.0     87   92.0
1  1080002  王倫樺   女  1080002@sun.tc.edu.tw     92  100.0   95.0     99   96.0
2  1080003  何宜敏   女  1080003@sun.tc.edu.tw     82   87.0   86.0     82   82.0
3  1080004  何志陞   男  1080004@sun.tc.edu.tw     91   92.0   99.0     91   92.0
4  1080005  吳ㄧ歌   女  1080005@sun.tc.edu.tw     93    NaN   92.0     97   98.0

### Remove duplicates

In [6]:
df[df.duplicated()]
df[df.duplicated(keep=False)] # 顯示所有重複的 rows
df.drop_duplicates(inplace=True)

### Clean data

In [8]:
# Remove rows with any -1 scores 缺考以-1表示
filter = (df['exam1'] == -1) | (df['exam2'] == -1) | (df['exam3'] == -1) | (df['exam4'] == -1) | (df['exam5'] == -1)
i = df[filter].index
print(i)
df.loc[i]
df.drop(i, axis = 0, inplace = True)

Index([8, 12], dtype='int64')

In [9]:
# Reindex the DataFrame
df.reset_index(drop=True, inplace=True)
df

         id name sex                  email  exam1  exam2  exam3  exam4  exam5
0   1080001  丁軒軒   男  1080001@sun.tc.edu.tw     86   88.0   82.0     87   92.0
1   1080002  王倫樺   女  1080002@sun.tc.edu.tw     92  100.0   95.0     99   96.0
2   1080003  何宜敏   女  1080003@sun.tc.edu.tw     82   87.0   86.0     82   82.0
3   1080004  何志陞   男  1080004@sun.tc.edu.tw     91   92.0   99.0     91   92.0
4   1080005  吳ㄧ歌   女  1080005@sun.tc.edu.tw     93    NaN   92.0     97   98.0
5   1080006  宋緯挺   男  1080006@sun.tc.edu.tw     84   81.0   83.0     90   88.0
6   1080007  李宇綸   女  1080007@sun.tc.edu.tw     82   76.0   89.0     87   85.0
7   1080009  杜以潔   女  1080009@sun.tc.edu.tw     53   56.0   57.0     54   53.0
8   1080010  沈程隆   男  1080010@sun.tc.edu.tw     81   77.0   84.0     86   83.0
9   1080011  沈慈惠   女  1080011@sun.tc.edu.tw     87   84.0   90.0     87   92.0
10  1080013  林保苓   女  1080013@sun.tc.edu.tw     92   94.0   99.0     96   94.0
11  1080014  林宏銘   男  1080014@sun.tc.edu.tw     60   56.0   58.0     85   88.0
12  1080015  邱堂儀   女  1080015@sun.tc.edu.tw     83   84.0   83.0     83   85.0
13  1080016  施帆蓉   女  1080016@sun.tc.edu.tw     87   90.0   92.0     86   92.0
14  1080017  胡祥傑   男  1080017@sun.tc.edu.tw     77   75.0   78.0     80   78.0
15  1080018  涂育婷   女  1080018@sun.tc.edu.tw     81   77.0   80.0     87   85.0
16  1080019  高二戈   男  1080019@sun.tc.edu.tw     80    NaN   77.0     88   83.0
17  1080020  高棋恩   男  1080020@sun.tc.edu.tw     88   88.0   87.0     87   92.0
18  1080021  張暐惠   女  1080021@sun.tc.edu.tw     84   89.0   83.0     85   84.0
19  1080022  梁承祐   男  1080022@sun.tc.edu.tw     87   91.0   90.0     86   92.0
20  1080023  許喬廷   女  1080023@sun.tc.edu.tw     85   87.0   86.0     85   86.0
21  1080024  許雅均   女  1080024@sun.tc.edu.tw     92   89.0   96.0     97   98.0
22  1080025  許銘婷   女  1080025@sun.tc.edu.tw     52   50.0   49.0     74   82.0
23  1080026  陳謙甄   女  1080026@sun.tc.edu.tw     82   88.0   81.0     81   86.0
24  1080027  陳生貞   男  1080027@sun.tc.edu.tw     97  100.0  100.0    100  100.0
25  1080028  陳宇愷   男  1080028@sun.tc.edu.tw     94   92.0   93.0     94  100.0
26  1080029  陳杰育   男  1080029@sun.tc.edu.tw     90   98.0   96.0     93   95.0
27  1080030  陳一潔   女  1080030@sun.tc.edu.tw     94   90.0  100.0     97    NaN
28  1080031  陳瑁揚   男  1080031@sun.tc.edu.tw     87   82.0   93.0     89   91.0
29  1080032  曾彥睿   男  1080032@sun.tc.edu.tw     78   81.0   78.0     79   83.0
30  1080033  黃杰弘   男  1080033@sun.tc.edu.tw     83   87.0   79.0     87   86.0
31  1080034  黃富穎   男  1080034@sun.tc.edu.tw     93   88.0   96.0     99   93.0
32  1080035  詹宗喻   男  1080035@sun.tc.edu.tw     87   87.0   89.0     88   89.0
33  1080036  廖安軒   女  1080036@sun.tc.edu.tw     91   92.0   97.0     91   94.0
34  1080037  劉隆霖   男  1080037@sun.tc.edu.tw     91   87.0   89.0     93   95.0
35  1080038  劉二婕   女  1080038@sun.tc.edu.tw     94  100.0    NaN     92   95.0
36  1080039  蔡凌嘉   男  1080039@sun.tc.edu.tw     94  100.0  100.0     94   95.0
37  1080040  謝穎安   男  1080040@sun.tc.edu.tw     78   82.0   81.0     79   80.0

In [10]:
# Handle missing values
df.isnull() # True:空值 False:非空值
df.isnull().sum() # 每個欄位有多少空值數

id       0
name     0
sex      0
email    0
exam1    0
exam2    2
exam3    1
exam4    0
exam5    1
dtype: int64

In [11]:
# Fill missing values with the mean of each exam
df[df['exam2'].isnull()] # 顯示exam2欄有空值的rows
df['exam2'] = df['exam2'].fillna(value = df['exam2'].mean())
df['exam3'] = df['exam3'].fillna(value = df['exam3'].mean())
df['exam5'] = df['exam5'].fillna(value = df['exam5'].mean())
df.isnull().sum() # 確認沒有空值了
df.describe()

                 id      exam1       exam2       exam3       exam4       exam5
count  3.800000e+01  38.000000   38.000000   38.000000   38.000000   38.000000
mean   1.080021e+06  84.526316   85.138889   86.135135   87.763158   88.702703
std    1.172880e+01  10.255485   11.316462   11.673861    8.358308    8.258869
min    1.080001e+06  52.000000   50.000000   49.000000   54.000000   53.000000
25%    1.080012e+06  82.000000   82.000000   81.250000   85.000000   85.000000
50%    1.080022e+06  87.000000   87.000000   88.000000   87.000000   90.000000
75%    1.080031e+06  91.750000   90.750000   94.500000   93.000000   94.000000
max    1.080040e+06  97.000000  100.000000  100.000000  100.000000  100.000000

In [12]:
# Change data types
df.dtypes
df['id'] = df['id'].astype('object')
df['exam1'] = df['exam1'].astype('int8')
df['exam2'] = df['exam2'].astype('int8')
df['exam3'] = df['exam3'].astype('int8')
df['exam4'] = df['exam4'].astype('int8')
df['exam5'] = df['exam5'].astype('int8')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      38 non-null     object
 1   name    38 non-null     object
 2   sex     38 non-null     object
 3   email   38 non-null     object
 4   exam1   38 non-null     int8
 5   exam2   38 non-null     int8
 6   exam3   38 non-null     int8
 7   exam4   38 non-null     int8
 8   exam5   38 non-null     int8
dtypes: int8(5), object(4)
memory usage: 1.5+ KB

### Transfer data

In [13]:
# In sex column, change '男' to 1 and '女' to 0
df['sex'] = df['sex'].map({'男': 1, '女': 0})
df['sex'] = df['sex'].astype('int8')
df.head()

        id name  sex                  email  exam1  exam2  exam3  exam4  exam5
0  1080001  丁軒軒    1  1080001@sun.tc.edu.tw     86     88     82     87     92
1  1080002  王倫樺    0  1080002@sun.tc.edu.tw     92    100     95     99     96
2  1080003  何宜敏    0  1080003@sun.tc.edu.tw     82     87     86     82     82
3  1080004  何志陞    1  1080004@sun.tc.edu.tw     91     92     99     91     92
4  1080005  吳ㄧ歌    0  1080005@sun.tc.edu.tw     93     85     92     97     98

# Pack script of data preprocessing

In [14]:
from pathlib import Path
import pandas as pd

# Load data
source_file = Path.cwd() / '../csv/student_scores.csv'
df = pd.read_csv(source_file)

# Change column names to english use replace method
df = df.rename(columns={
    'ID': 'id',
    '第1次平時考': 'exam1',
    '第2次平時考': 'exam2',
    '第3次平時考': 'exam3',
    '第4次平時考': 'exam4',
    '第5次平時考': 'exam5'
})

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Remove rows with any -1 scores 缺考以-1表示
filter = (df['exam1'] == -1) | (df['exam2'] == -1) | (df['exam3'] == -1) | (df['exam4'] == -1) | (df['exam5'] == -1)
i = df[filter].index
df.drop(i, axis = 0, inplace = True)

# Handle missing values
df['exam2'] = df['exam2'].fillna(value = df['exam2'].mean())
df['exam3'] = df['exam3'].fillna(value = df['exam3'].mean())
df['exam5'] = df['exam5'].fillna(value = df['exam5'].mean())

# In sex column, change '男' to 1 and '女' to 0
df['sex'] = df['sex'].map({'男': 1, '女': 0})

# Change data types
df['id'] = df['id'].astype('str')
df['exam1'] = df['exam1'].astype('int8')
df['exam2'] = df['exam2'].astype('int8')
df['exam3'] = df['exam3'].astype('int8')
df['exam4'] = df['exam4'].astype('int8')
df['exam5'] = df['exam5'].astype('int8')
df['sex'] = df['sex'].astype('int8')

# Reindex the DataFrame
df.reset_index(drop=True, inplace=True)

# Save cleaned data to new CSV file
df.head()
df.info()
output_file = Path.cwd() / '../csv/student_scores_cleaned.csv'
df.to_csv(output_file, index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      38 non-null     object
 1   name    38 non-null     object
 2   sex     38 non-null     int8
 3   email   38 non-null     object
 4   exam1   38 non-null     int8
 5   exam2   38 non-null     int8
 6   exam3   38 non-null     int8
 7   exam4   38 non-null     int8
 8   exam5   38 non-null     int8
dtypes: int8(6), object(3)
memory usage: 1.2+ KB